FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN go install github.com/swaggo/swag/cmd/swag@v1.16.3

COPY go.mod go.sum ./
RUN go mod download

# Копіюй код
COPY . .

RUN rm -rf docs/

RUN swag init -g cmd/app/main.go

RUN CGO_ENABLED=0 GOOS=linux go build -tags dev -o /usr/local/bin/darts github.com/dimqueue/darts/cmd/app

FROM alpine:3.19

RUN apk add --no-cache ca-certificates

COPY --from=builder /usr/local/bin/darts /usr/local/bin/darts

EXPOSE 8080

ENTRYPOINT ["darts"]