services:
  backend:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: ${BUILD_MODE:-prod}  # defaults to prod, override with env var
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command: run-server # migrates-up migrates-down run-server
    volumes:
      - ./configs/config.yml:/configs/config.yml:ro

  db:
    restart: on-failure
    image: postgres:16-alpine
    container_name: dartsdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: