export const mockWords = {
    en: ['ocean', 'mountain', 'love', 'time', 'music', 'dream', 'journey', 'light'],
    ua: ['океан', 'гора', 'любов', 'час', 'музика', 'мрія', 'подорож', 'світло'],
};

export const similarityMap = {
    ocean: {
        sea: 5,
        water: 12,
        wave: 25,
        beach: 45,
        fish: 80,
        ship: 95,
        blue: 120,
        deep: 150,
        salt: 180,
        marine: 35,
        tide: 55,
        surf: 60,
        coral: 110,
        whale: 70,
        dolphin: 75,
        swim: 140,
        dive: 135,
        lake: 200,
        river: 220,
        pond: 280,
    },
    mountain: {
        hill: 15,
        peak: 8,
        summit: 10,
        rock: 45,
        cliff: 35,
        climb: 60,
        snow: 90,
        alpine: 25,
        valley: 70,
        hiking: 85,
        everest: 40,
        high: 110,
        elevation: 55,
        range: 50,
        forest: 180,
        nature: 200,
        stone: 140,
        trail: 120,
    },
    love: {
        heart: 10,
        romance: 15,
        passion: 25,
        affection: 20,
        care: 45,
        emotion: 60,
        feeling: 55,
        kiss: 35,
        hug: 40,
        relationship: 70,
        marriage: 85,
        wedding: 90,
        happiness: 110,
        joy: 120,
        family: 150,
        friend: 180,
        like: 95,
        adore: 30,
    },
    time: {
        clock: 15,
        hour: 20,
        minute: 25,
        second: 30,
        moment: 35,
        duration: 45,
        period: 50,
        era: 60,
        age: 65,
        history: 90,
        future: 80,
        past: 75,
        present: 70,
        watch: 40,
        calendar: 55,
        date: 85,
        schedule: 100,
        eternal: 120,
    },
    music: {
        song: 8,
        melody: 12,
        rhythm: 20,
        sound: 35,
        instrument: 45,
        guitar: 55,
        piano: 60,
        drum: 65,
        singer: 40,
        band: 50,
        concert: 70,
        dance: 85,
        note: 25,
        harmony: 30,
        orchestra: 75,
        radio: 110,
        audio: 95,
        listen: 80,
    },
    dream: {
        sleep: 15,
        nightmare: 35,
        vision: 25,
        fantasy: 30,
        imagination: 40,
        hope: 55,
        wish: 50,
        aspiration: 45,
        goal: 70,
        night: 60,
        bed: 85,
        rest: 90,
        subconscious: 65,
        thought: 100,
        mind: 95,
        wonder: 75,
        magic: 110,
    },
    journey: {
        travel: 8,
        trip: 12,
        voyage: 15,
        adventure: 25,
        expedition: 35,
        road: 45,
        path: 40,
        destination: 55,
        explore: 50,
        wander: 60,
        tour: 30,
        vacation: 70,
        flight: 85,
        car: 120,
        train: 110,
        walk: 95,
        mile: 80,
    },
    light: {
        bright: 10,
        sun: 20,
        lamp: 35,
        glow: 25,
        shine: 15,
        beam: 30,
        ray: 28,
        illuminate: 40,
        flash: 45,
        sparkle: 50,
        dark: 150,
        shadow: 140,
        candle: 60,
        bulb: 55,
        fire: 90,
        star: 70,
        moon: 85,
        electric: 100,
    },

    океан: {
        море: 5,
        вода: 12,
        хвиля: 25,
        пляж: 45,
        риба: 80,
        корабель: 95,
        синій: 120,
        глибина: 150,
        сіль: 180,
        морський: 35,
        прилив: 55,
        серфінг: 60,
        корал: 110,
        кит: 70,
        дельфін: 75,
        плавати: 140,
        пірнати: 135,
        озеро: 200,
        річка: 220,
    },
    гора: {
        пагорб: 15,
        вершина: 8,
        пік: 10,
        скеля: 45,
        обрив: 35,
        підйом: 60,
        сніг: 90,
        альпійський: 25,
        долина: 70,
        похід: 85,
        високий: 110,
        висота: 55,
        хребет: 50,
        ліс: 180,
        природа: 200,
        камінь: 140,
        стежка: 120,
    },
    любов: {
        серце: 10,
        романтика: 15,
        пристрасть: 25,
        почуття: 60,
        емоція: 55,
        поцілунок: 35,
        обійми: 40,
        стосунки: 70,
        шлюб: 85,
        весілля: 90,
        щастя: 110,
        радість: 120,
        родина: 150,
        друг: 180,
        кохання: 5,
        обожнювати: 30,
    },
    час: {
        годинник: 15,
        година: 20,
        хвилина: 25,
        секунда: 30,
        мить: 35,
        період: 50,
        ера: 60,
        вік: 65,
        історія: 90,
        майбутнє: 80,
        минуле: 75,
        сьогодення: 70,
        календар: 55,
        дата: 85,
        вічність: 120,
    },
    музика: {
        пісня: 8,
        мелодія: 12,
        ритм: 20,
        звук: 35,
        інструмент: 45,
        гітара: 55,
        піаніно: 60,
        барабан: 65,
        співак: 40,
        гурт: 50,
        концерт: 70,
        танець: 85,
        нота: 25,
        гармонія: 30,
        оркестр: 75,
        радіо: 110,
        слухати: 80,
    },
    мрія: {
        сон: 15,
        кошмар: 35,
        бачення: 25,
        фантазія: 30,
        уява: 40,
        надія: 55,
        бажання: 50,
        мета: 70,
        ніч: 60,
        ліжко: 85,
        відпочинок: 90,
        думка: 100,
        розум: 95,
        диво: 75,
        магія: 110,
    },
    подорож: {
        мандрівка: 8,
        поїздка: 12,
        пригода: 25,
        експедиція: 35,
        дорога: 45,
        шлях: 40,
        напрямок: 55,
        дослідження: 50,
        тур: 30,
        відпустка: 70,
        політ: 85,
        машина: 120,
        потяг: 110,
        ходьба: 95,
    },
    світло: {
        яскравий: 10,
        сонце: 20,
        лампа: 35,
        сяйво: 25,
        блиск: 15,
        промінь: 28,
        освітлення: 40,
        спалах: 45,
        іскра: 50,
        темрява: 150,
        тінь: 140,
        свічка: 60,
        вогонь: 90,
        зірка: 70,
        місяць: 85,
        електричний: 100,
    },
};

export function getRandomWord(language) {
    const words = mockWords[language] || mockWords.en;
    return words[Math.floor(Math.random() * words.length)];
}

export function calculateDistance(guess, target) {
    const normalizedGuess = guess.toLowerCase().trim();
    const normalizedTarget = target.toLowerCase().trim();

    if (normalizedGuess === normalizedTarget) {
        return 1;
    }

    const targetSimilarities = similarityMap[normalizedTarget];
    if (targetSimilarities && targetSimilarities[normalizedGuess] !== undefined) {
        return targetSimilarities[normalizedGuess];
    }

    return Math.floor(Math.random() * 600) + 300;
}
