port: "8080"

db:
  host: "localhost" # dartsdb localhost
  username: "admin"
  port: "5432"
  dbname: "dartsdb"
  sslmode: "disable"

word-service:
  type: "http"
  baseURL: "http://localhost:5000"
  timeout: 30